import type { Metadata } from "next";
import Image from "next/image";
import { Montserrat } from "next/font/google";
import "./globals.css";

import BottomVector from "@/assets/vector.svg";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`relative ${montserrat.className}`}>
        {children}
        <Image
          src={BottomVector}
          alt="bottom-vector"
          className="w-full absolute bottom-0 left-0"
        />
      </body>
    </html>
  );
}
